services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: qr-app-backend
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./front-end-nextjs
      dockerfile: Dockerfile
    container_name: qr-app-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
