grafana:
  admin:
    existingSecret: grafana-admin-secret
    existingSecretPasswordKey: admin-password
  persistence:
    enabled: false # data lost when pod dies, but cost-saving (don't use in production)
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

prometheus:
  prometheusSpec:
    resources:
      requests:
        cpu: 200m
        memory: 400Mi
      limits:
        cpu: 500m
        memory: 800Mi
    retention: 6h # Prometheus only keeps 6 hours of metrics history instead of the default 10 days.

alertmanager:
  enabled: false

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true