apiVersion: v1
kind: Service
metadata:
  name: qr-api-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: qr-api
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
  type: ClusterIP