apiVersion: v1
kind: Service
metadata:
  name: qr-frontend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: qr-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
  type: ClusterIP