apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qr-api-servicemonitor
  namespace: {{ .Values.namespace }}
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: qr-api
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s  # change interval if you desire.