apiVersion: v1 
kind: Service 
metadata:
  name: qr-frontend-service 
  namespace: qr-code-app 
spec:
  selector:
    app: qr-frontend
  ports:
    - port: 3000 
      targetPort: 3000
  type: LoadBalancer

# type: LoadBalancer ?
# this tells EKS's AWS integration to provision a real AWS load balancer with a public address,
# so you can actually open the app in a browser from outside the cluster